apiVersion: v1
kind: Service
metadata:
  name: {{ include "futbalmng-client.fullname" . }}
  labels:
    {{- include "futbalmng-client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "futbalmng-client.selectorLabels" . | nindent 4 }}
