name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: docker build . -t tomzreacr.azurecr.io/futbalmng-client 
    - name: login to CR
      run: docker login -u tomzreacr -p $CI_REGISTRY_TOKEN tomzreacr.azurecr.io
      env:
          CI_REGISTRY_TOKEN: ${{ secrets.CONTAINER_PWD }}
    - name: push to CR
      run: docker push tomzreacr.azurecr.io/futbalmng-client
